---
url: https://github.com/BR0kEN-/ha-dtek-shutdowns
name: "DTEK Outages Checker"
slug: "ha-dtek-shutdowns"
version: "1.2.5"
description: "Visits the DTEK website to check the outages for your address and forms an ICS calendar."
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8084/tcp: 8084
options:
  region: dnem
  locality: ""
  street: ""
  building: ""
schema:
  region: "list(dnem|kem|krem|oem)"
  locality: "str"
  street: "str"
  building: "str"
